### ISSUE TITLE
Linear filter has rounding errors

### ISSUE THREAD

**Issue by tpoisot** [PoisotLab/EcologicalNetworks.jl#115]
In some situations (I don't know which exactly) the `linearfilter` can generate probabilities of `1.0000...1` -- this usually send the whole analysis crashing down.

**Comment by MichielStock** [comment]
Is solving this by returning `max.(min.(F, 1.0), 0.0)` in the linear filter an option?

**Comment by tpoisot** [comment]
Possibly -- I just pushed something with this fix.
