### ISSUE TITLE
Information theory indices

### ISSUE THREAD

**Issue by MichielStock** [PoisotLab/EcologicalNetworks.jl#117]
As mentioned, we would implement some functions to do an information theoretic decomposition of the interaction matrices in:

- difference in entropy compared to uniform marginals;
- mutual information;
- variance of information.

For every component, a function is provided that:

- returns this for either both or one of the trophic levels;
- provides the true values (in nats or bits) or normalizes these that they sum to one.

I'll make a new file `community/information.jl` in a new branch.

Work together with @lhoebeke. We might also look into some visualisation methods.

**Comment by tpoisot** [comment]
I love this idea. Please go ahead and make a branch from `develop`. There is a very tentative package for visualisation at https://github.com/PoisotLab/EcologicalNetworksPlots.jl

**Comment by MichielStock** [comment]
Yes, I used that one, might ask for a bit of help with this 😬
We might also add a [Finetti diagram](https://en.wikipedia.org/wiki/De_Finetti_diagram) or something with a stacked bar plot to this end.

**Comment by tpoisot** [comment]
Well as it stands, `EcologicalNetworksPlots.jl` is not really flexible, and I will definitely work on that soon. I need to get `EcologicalNetworks.jl` released before, and we're waiting on reviews for a software note.

**Comment by lhoebeke** [comment]
Indices that will be implemented:
- [ ] entropy
    - [ ] joint
    - [ ] marginal
    - [ ] conditional
- [ ] mutual information
- [ ] variation of information
- [ ] entropy of corresponding uniform distribution
    - [ ] joint
    - [ ] marginal
- [ ] difference in entropy compared to uniform distribution
    - [ ] joint
    - [ ] marginal
- [ ] conversion to effective number of interactions

**Comment by tpoisot** [comment]
Excellent! I think it's worth adding
- [ ] a new `informationtheory` folder into `src`
- [ ] a new `informationtheory` folder into `test`
- [ ] a new page or section to the documentation

**Comment by MichielStock** [comment]
All ready in a branch in my [fork](https://github.com/MichielStock/EcologicalNetworks.jl/tree/informationtheory).

@lhoebeke: You might want to clone this together with `Julia 0.7`

**Comment by MichielStock** [comment]
**Update**: everything is implemented, documented and has unit-tests. @lhoebeke: you can check this off.

We only have to write the corresponding page in the documentation. Better wait with this until we advance in the manuscript to finalize this.

**Comment by tpoisot** [comment]
@MichielStock / @lhoebeke we are about to re-submit a version of the software note -- do you wish to see these measures in the published version, and if so share co-authorship?

**Comment by gvdr** [comment]
@MichielStock any plan to throw in the bundle some complexity indices (such as the ones discussed [here](https://doi.org/10.1016/j.physa.2008.01.015) )?

**Comment by MichielStock** [comment]
I can add them at the long run, if only as an exercise in Julia. At the moment however, we are focussed on finishing the standard information theory indices. 

I'll check the paper out though!
