### ISSUE TITLE
Compute stability parameter

### ISSUE THREAD

**Issue by MichielStock** [PoisotLab/EcologicalNetworks.jl#129]
I will add the stability parameter from this [article](https://www.nature.com/articles/nature16948), which quantifies the dynamics of a network.

Will add this in new file `community/dynamics.jl`.

If deemed relevant, the more general reduction of [this more recent paper](https://journals.aps.org/prx/pdf/10.1103/PhysRevX.9.011042) can be added as well.

**Comment by tpoisot** [comment]
:+1:

**Comment by MichielStock** [comment]
Implemented. I will open a PR for review. Think that the docs can still be improved though.
