### ISSUE TITLE
New null model

### ISSUE THREAD

**Issue by MichielStock** [PoisotLab/EcologicalNetworks.jl#130]
As I mentioned some time ago on the slack, I think it would also make sense to have a version of the null model of type two where the probability of an interaction is proportional to the **product** of the degree distributions. This would be a true neutral model, as the probability of interaction between two levels is independent.

(Though I also appreciate the `null2` as a special case of the linear filter).

I added a new function as follows:

```julia
"""
    null2mult(N::BinaryNetwork)

Given a matrix `A`, `null2mult(A)` returns a matrix with the same dimensions, where
every interaction happens with a probability equal to the product of the degree
of each species.
"""
function null2mult(N::BinaryNetwork)
  A = N.A
  n, m = size(A)
  Afiltered = sum(A, dims=1) .* sum(A, dims=2) ./ sum(A)^2
  if typeof(N) <: AbstractBipartiteNetwork
  return BipartiteProbabilisticNetwork(Afiltered)
  else
    return UnipartiteProbabilisticNetwork(Afiltered)
  end
end
```

I also updated the testing and docs. 

Would you agree that this is a sensible thing to add? If so, I can open a pull request.

**Comment by MichielStock** [comment]
Reading this, I think that the docs are a bit outdated (`Given a matrix A` => should be a network). Shall I update this as well?

**Comment by tpoisot** [comment]
Sounds like a good idea, open a PR.
