### ISSUE TITLE
Info about upcoming removal of packages in the General registry

### ISSUE THREAD

**Issue by KristofferC** [PoisotLab/EcologicalNetworks.jl#145]
As described in https://discourse.julialang.org/t/ann-plans-for-removing-packages-that-do-not-yet-support-1-0-from-the-general-registry/ we are planning on removing packages that do not support 1.0 from the General registry. This package has been detected to not support 1.0 and is thus slated to be removed. The removal of packages from the registry will happen approximately a month after this issue is open.

To transition to the new Pkg system using `Project.toml`, see https://github.com/JuliaRegistries/Registrator.jl#transitioning-from-require-to-projecttoml.
To then tag a new version of the package, see https://github.com/JuliaRegistries/Registrator.jl#via-the-github-app.

If you believe this package has erroneously been detected as not supporting 1.0 or have any other questions, don't hesitate to discuss it here or in the thread linked at the top of this post.

**Comment by tpoisot** [comment]
This package definitely works on 1.0

**Comment by KristofferC** [comment]
Will check what went wrong.,

**Comment by KristofferC** [comment]
Okay, this is actually about the package "EcologicalNetwork" which points towards this repo. That one is ok to remove, correct?

**Comment by tpoisot** [comment]
Absolutely! We renamed the package after comments from reviewers.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
