### ISSUE TITLE
GPU compatability 

### ISSUE THREAD

**Issue by gottacatchenall** [PoisotLab/EcologicalNetworks.jl#191]
As part of [MetacommunityDynamics.jl](https://github.com/EcoJulia/MetacommunityDynamics.jl/), we want to be able to use EN.jl types and generative models on GPUs.

Here's a running list of my understanding of the changes required to use EN.jl with [DynamicGrids.jl](https://github.com/cesaraustralia/DynamicGrids.jl) on a GPU:

 - [ ] Non-mutable structs for (Unipartite/Bipartite) networks. This could be done via a wrapper around `UnipartiteNetwork` and `BipartiteNetwork` (e.g. `GPUUnipartiteNetwork`)

**Comment by rafaqz** [comment]
A few points of clarification. A wrapper wouldn't be sufficient, as none of the contents can be mutable either. The object needs to be `isbits(obj) = true`. What could be required is e.g. a `StaticUnipartideNetwork` built on StaticArrays.jl and modified with Accessors.jl.

Additionally, this is required to work with DynamicGrids.jl even on CPU.

**Comment by gottacatchenall** [comment]
> Additionally, this is required to work with DynamicGrids.jl even on CPU. 

This is only in the case that you want to use a `UnipartiteNetwork`/`BipartiteNetwork` as a custom grid-element, correct? This may be the case for some applications but not all

**Comment by rafaqz** [comment]
Yep as the content of a grid on CPU, and as any part of a model on GPU. I don't really know how this package works :)

**Comment by rafaqz** [comment]
It's also possible to use immutable structs for the networks and swap the `Vector`s for `CuArray`, if the networks are just fields in a rule.

**Comment by tpoisot** [comment]
So... the types used to be immutable (but not the content of the fields), and it was a lot more trouble for many, many applications. But this is clearly something I'd like to have at some point. I'm happy to discuss more.

**Comment by gottacatchenall** [comment]
I think a possible solution here would be wrapper types which via macro could convert as-existing EN.jl network types to immutable prior to deploying on GPU
