### ISSUE TITLE
simplify!

### ISSUE THREAD

**Issue by JennieLavine** [PoisotLab/EcologicalNetworks.jl#198]
The simplify! command doesn't remove elements with only self-connections, and therefore takes a degenerate graph and returns a degenerate graph.

**To Reproduce**

~~~julia
testM = Bool[1 1 0; 1 1 0; 0 0 1]
testNet = UnipartiteNetwork(testM)
isdegenerate(testNet)
simplify!(testNet)
isdegenerate(testNet)
~~~

**Expected behavior**
simplify! should take out element 3 since it is connected only to itself

In contrast, when element 3 is NOT connected to itself, it is appropriately removed when 'simplify!' is used.  See example below where the bottom right element in the matrix is changed to a zero.

~~~julia
testM2 = Bool[1 1 0; 1 1 0; 0 0 0]
testNet = UnipartiteNetwork(testM2)
isdegenerate(testNet)
simplify!(testNet)
testNet
isdegenerate(testNet)
~~~

**Comment by tpoisot** [comment]
Hi @JennieLavine - the way to force networks to drop nodes with self interactions is to add `nodiagonal` before, so in your case 

~~~ julia
testNet |> nodiagonal |> simplify
~~~

Do you think the documentation needs a clarification? Happy to hear where you think it will be more useful.
