### ISSUE TITLE
`trophic_level` gives unrealistically big values

### ISSUE THREAD

**Issue by FrancisBanville** [PoisotLab/EcologicalNetworks.jl#207]
**Describe the bug**
When computing the maximum trophic level of some networks, the `trophic_level` function returns unrealistically big values (i.e., orders of magnitude bigger than what we would expect for food webs).  Out of 1399 (simplified) networks in my analysis, the function returned a maximum trophic level of more than 50 for 63 networks (5%), while most of them had a species richness of less than 50. We believe this might mostly be due to numerical instability with the new version of the function.

**To Reproduce**
This is one example of a matrix that gives a maximum trophic level of 4.05e16:
```julia
mat = [0 0 0 1 0 0 0 0 0; 0 0 0 1 0 0 0 0 0; 0 0 0 0 0 0 1 0 0; 0 1 1 0 1 0 0 0 0; 0 0 0 0 0 0 1 1 0; 0 0 0 0 0 0 0 1 0; 1 0 0 0 0 0 0 0 1; 0 0 0 0 0 1 1 0 0; 0 0 0 0 0 1 0 1 0]
N = UnipartiteNetwork(convert(Matrix{Bool}, mat))
maxtl = maximum(values(trophic_level(N)))
```

**Expected behavior**
We should expect the function to return a maximum trophic level of less than around 20 (or at least less than the number of species), an error message, or missing values. 

**Desktop**
 - OS: Windows 10
 - Version: EcologicalNetworks.jl v0.5.2

**Comment by mjsmith037** [comment]
When I run this code (Linux Mint 20.3; EcologicalNetworks.jl v0.5.2). I get a maximum trophic level of 1.41, though I also get some negative values:

```
julia>trophic_level(N)
Dict{String, Float64} with 9 entries:
  "s1" => 1.1077
  "s8" => -1.29503
  "s5" => -0.0288206
  "s6" => -1.37012
  "s7" => -0.148275
  "s2" => 1.41487
  "s4" => 0.722033
  "s9" => -0.946909
  "s3" => 0.544558
```
Note, these values are based on the input `mat` being structured such that `mat[i, j] == 1` signifies that species `i` eats species `j`
